name: mlcourse_latest
channels:
  - pytorch
  - defaults
  - conda-forge
dependencies:
  - python
  - pip
  - numpy
  - scipy
  - scikit-learn 
  - scikit-image
  - pandas
  - matplotlib
  - pylops
  - ipython
  - jupyter
  - pytorch=1.12.0
  - torchvision=0.13.0
  - torchaudio=0.12.0
  - lightgbm
  - xgboost
  - tqdm 
  - pip:
    - torchsummary
    - torchviz
    - pytorch-lightning
    - scooby
    - lasio
    - segyio
    - seaborn
    - wandb
